### get all product
GET http://localhost:3000/api/product


### get single product
GET http://localhost:3000/api/product/646731127ca01f0f4fe382dc


### create new product
POST http://localhost:3000/api/product
Content-Type: application/json


{
  "name": "Shure SM7B Cardioid Dynamic Microphone",
  "price": 349,
  "description": "The Shure SM7B is a cardioid dynamic microphone that is designed for use in a variety of settings, including live performances, podcasting, and home recording. It features a smooth, flat, wide-range frequency response and a built-in pop filter and shock mount for reduced noise and handling noise.",
  "category": "electronics",
  "seller": "Shure",
  "stock": 5,
  "images": [
    {
      "id": "buyitnow/products/gclqht0hjco0jyy9s2bx",
      "url": "http://res.cloudinary.com/shopitnow-udemy/image/upload/v1674393848/buyitnow/products/gclqht0hjco0jyy9s2bx.jpg"
    },
    {
      "id": "buyitnow/products/qdilqh5oizvnwfu2bkzq",
      "url": "http://res.cloudinary.com/shopitnow-udemy/image/upload/v1674393852/buyitnow/products/qdilqh5oizvnwfu2bkzq.jpg"
    },
    {
      "id": "buyitnow/products/cjtvzn5crbcyddo2hlai",
      "url": "http://res.cloudinary.com/shopitnow-udemy/image/upload/v1674393855/buyitnow/products/cjtvzn5crbcyddo2hlai.jpg"
    }
  ],
  "reviews": [],
  "rating": 4.5
}


### singup
POST http://localhost:3000/api/auth/singup
Content-Type: application/json

{
  "name": "nirob",
  "email": "nirob@mail.com",
  "password": "12345678"
}


### singin
POST http://localhost:3000/api/auth/singin
Content-Type: application/json

{
  "email": "nirob@mail.com",
  "password": "12345678"
}



### singup
POST http://localhost:3000/api/address
Content-Type: application/json

{
  "country": "india",
  "street": "sonapur road",
  "city": "dhaka",
  "state": "kovirhat",
  "phone": "01881614926",
  "zip": "3800"
}

### get al addresses fix issue get all address by single user 
GET http://localhost:3000/api/address
