@host = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY0ODU4ZjlmYmEwNDQ5ZTYxOTgyM2Q5ZiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4NjQ3NDY1NX0.Ca-NA7R5AudkwmVCJD5oDe6w62jaw-3uiYOg6gqMP1o


# @name
POST {{host}}/order/checkout
Authorization: Bearer {{token}}

{
  "items": [
    {
      "name": "unknown",
      "price": 40,
      "quantity":2,
      "imageURL": "googl.com",
      "id": "646d10913fd553b04ed72571"
    }
  ],
  "addressId": "646d10913fd553b04ed72571"
}



### 
GET {{host}}/order/get-orders
Authorization: Bearer {{token}}
Content-Type: application/json
